[workspace]
resolver = "2"
members = [
    "crates/tusher-core",
    "crates/tusher-network",
    "crates/tusher-transfer",
    "crates/tusher-metadata",
    "crates/tusher-sync",
    "crates/tusher-cli",
    "crates/tusher-ffi",
    "crates/tusher-desktop",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["Tusher Mondal"]
license = "MIT"

[workspace.dependencies]
tokio = { version = "1.38", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ed25519-dalek = { version = "2.1", features = ["rand_core", "serde"] }
rand = "0.8"
sha2 = "0.10"
hmac = "0.12"
data-encoding = "2.6"
hex = "0.4"
chrono = { version = "0.4", features = ["serde"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
async-trait = "0.1"
anyhow = "1.0"
thiserror = "2"
clap = { version = "4.5", features = ["derive"] }
socket2 = "0.5"
rusqlite = { version = "0.32", features = ["bundled"] }
notify = "6.1"
uniffi = { version = "0.28", default-features = false }
uniffi_bindgen = "0.28"

