[package]
name = "tusher-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[[bin]]
name = "tusher"
path = "src/main.rs"

[dependencies]
tusher-core = { path = "../tusher-core" }
tusher-network = { path = "../tusher-network" }
tusher-transfer = { path = "../tusher-transfer" }
tusher-metadata = { path = "../tusher-metadata" }
tusher-sync = { path = "../tusher-sync" }
tokio.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
serde_json.workspace = true
